-- Generated by Flavours (Everforest Dark (Base24 fallback) (Base46) by xxx) - do not edit manually
return {
  base00 = "#2b3339", base01 = "#323c41", base02 = "#3a464c", base03 = "#859289",
  base04 = "#9da9a0", base05 = "#d3c6aa", base06 = "#e4e1cd", base07 = "#fdf6e3",
  base08 = "#e67e80", base09 = "#e69875", base0A = "#dbbc7f", base0B = "#a7c080",
  base0C = "#83c092", base0D = "#7fbbb3", base0E = "#d699b6", base0F = "#eaedc8",
  base10 = "#2b3339", base11 = "#2b3339", base12 = "#e67e80", base13 = "#dbbc7f",
  base14 = "#a7c080", base15 = "#83c092", base16 = "#7fbbb3", base17 = "#d699b6",
  base18 = "#925c60", base19 = "#926b5a", base1A = "#8c7e60", base1B = "#6f8160",
  base1C = "#5b816a", base1D = "#597e7c", base1E = "#896b7e", base1F = "#949988",
  base20 = "#323c41", base21 = "#3e4749", base22 = "#4b5151", base23 = "#575c59",
  base24 = "#646661", base25 = "#707169", base26 = "#7c7c71", base27 = "#89867a",
  base28 = "#959182", base29 = "#a19c8a", base2A = "#aea692", base2B = "#bab19a",
  base2C = "#c7bba2", base2D = "#d3c6aa",
}